import type { Metadata } from "next";
import { Inter, Nabla } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/navbar";
import { getSession } from "../helper/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code demo",
  description: "Generated by Youssef",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        {session && <Navbar />}
        {children}
      </body>
    </html>
  );
}
